[tool.poetry]
name = "travel-planner-ai"
version = "0.1.0"
description = "Travel Planner AI using FastAPI, GPT-4o, and React"
authors = ["Vitalii Kudriavtcev <vkusa87@gmail.com>"]
packages = [
    { include = "travel_planner_ai" }
]


[tool.poetry.dependencies]
python = "^3.11.0"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
motor = "^3.3.2"
pydantic = "^2.6.1"
python-dotenv = "^1.0.0"
openai = "^1.12.0"
cachetools = "^5.3.2"

[poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
